spring.application.name=chatapp-second
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp_second
spring.datasource.username= user
spring.datasource.password= 3205
spring.flyway.baselineOnMigrate=true